# Generated by Django 6.1.1 on 2026-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orca', '0002_userrole_django_orca_role_cl_3e0010_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='object_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
