# Generated by Django 6.1.1 on 2026-09-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_orca', '0003_userrole_object_id_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
