---
repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]
        exclude: ".*/migrations/.*"

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: ".*/migrations/.*"

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.3.0
    hooks:
      - id: flakeheaven
        exclude: ".*/migrations/.*"

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
      - id: markdownlint-cli2
