site_name: django_orca

theme:
  name: material

nav:
  - index.md
  - views.md

plugins:
- search  
- mkdocstrings

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
