# Generated by Django 6.1.1 on 2026-09-25 20:04

import django.db.models.deletion
import django_orca.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_honorscourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            bases=(django_orca.models.RoleMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            bases=(django_orca.models.RoleMixin, models.Model),
        ),
    ]
