# Generated by Django 4.2.4 on 2023-08-14 20:32

import django.db.models.deletion
import django_orca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_department_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            bases=(django_orca.models.RoleMixin, models.Model),
        ),
        migrations.AddField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.school"
            ),
        ),
    ]
