# Generated by Django 4.2.4 on 2023-08-31 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_school_department_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="HonorsCourse",
            fields=[
                (
                    "course_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.course",
                    ),
                ),
            ],
            bases=("main.course",),
        ),
    ]
